# Generated by Django 4.1.4 on 2022-12-16 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('kitnet', 'Kitnet'), ('casa', 'Casa')], max_length=30)),
                ('endereco', models.CharField(max_length=40)),
                ('valor', models.CharField(max_length=8)),
            ],
        ),
    ]
